### ISSUE TITLE
Nice G.O. failing to setup

### ISSUE THREAD

**Issue by splasheye** [IceBotYT/nice-go#95]
Hi I just updated my Home Assistant to 2024.9.2 and added Nice G.O. Integration, but its failing to set up.
this is a copy from my log file.

Logger: homeassistant.components.nice_go.coordinator
Source: helpers/update_coordinator.py:293
integration: Nice G.O. (documentation, issues)
First occurred: 9:26:33 AM (79 occurrences)
Last logged: 10:59:34 AM

Unexpected error fetching Nice G.O. data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 293, in __wrap_async_setup
    await self._async_setup()
  File "/usr/src/homeassistant/homeassistant/components/nice_go/coordinator.py", line 142, in _async_setup
    await self._parse_barrier(barrier.state) for barrier in barriers
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/nice_go/coordinator.py", line 103, in _parse_barrier
    light_status = barrier_state.reported["lightStatus"].split(",")[0] == "1"
                   ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'lightStatus'

Any help would be great.

Thanks.

**Comment by IceBotYT** [comment]
Hi there! Please move this to the core repository so I can assist you better. Thank you :)

https://github.com/home-assistant/core/issues/new?assignees=&labels=&projects=&template=bug_report.yml
